<?php

Use App\Player;
use Illuminate\Database\Seeder;

class PlayerTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
  public function run(){

    $players = [

    //ATLETICO DE MADRID
    ['team_id' => 1, 'name' => 'Alexis Sánchez', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Bartra', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Bellarabi', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Benzema', 'goals_club' => 15, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Bolasie', 'goals_club' => 8, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Bony', 'goals_club' => 8, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Bravo', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Busquets', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Cavani', 'goals_club' => 13, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Cazorla', 'goals_club' => 6, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'David Luiz', 'goals_club' => 4, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Diego Costa', 'goals_club' => 3, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Embolo', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Falcao', 'goals_club' => 9, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Fernando Torres', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Filipe Luis', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Fábregas', 'goals_club' => 3, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Hummels', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Iñaki Williams', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Juanfran', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Kane', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Konoplyanka', 'goals_club' => 18, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Lahmn', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Mandzuckic', 'goals_club' => 4, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Miranda', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Naldo', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Nolito', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Ozil', 'goals_club' => 3, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Pastore', 'goals_club' => 4, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Payet', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Piqué', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Rakitic', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Raul García', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'RESTO', 'goals_club' => 85, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Rode', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Sneijder', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Tevez', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Vardy', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Wallcot', 'goals_club' => 10, 'goals_career' => 0],
    ['team_id' => 1, 'name' => 'Zabaleta', 'goals_club' => 0, 'goals_career' => 0],


    //CHELSEA
    ['team_id' => 2, 'name' => 'Alex Sandro', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Alexis Sánchez', 'goals_club' => 4, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Asensio', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Aubameyang', 'goals_club' => 3, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Azpilicueta', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Baba', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Balotelli', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Barzagli', 'goals_club' => 4, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Benteke', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Bertrand Traoré', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Boateng', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Carrasco', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Cavani', 'goals_club' => 10, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Coleman', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Cristiano Ronaldo', 'goals_club' => 30, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Cuadrado', 'goals_club' => 6, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Danilo Pereira', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'David Luiz', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'De Bruyne', 'goals_club' => 11, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Denis Suarez', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Diego Costa', 'goals_club' => 13, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Douglas Costa', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Dybala', 'goals_club' => 21, 'goals_career' => 1],
    ['team_id' => 2, 'name' => 'Fábregas', 'goals_club' => 3, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Gervinho', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Gotze', 'goals_club' => 4, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Hazard', 'goals_club' => 17, 'goals_career' => 2],
    ['team_id' => 2, 'name' => 'Higuaín', 'goals_club' => 12, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Jackson', 'goals_club' => 7, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Javi Martínez', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Konoplyanka', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Kramer', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Lacazette', 'goals_club' => 5, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Laporte', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Lichsteiner', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Lucas', 'goals_club' => 8, 'goals_career' => 1],
    ['team_id' => 2, 'name' => 'Luiz Gustavo', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Marchisio', 'goals_club' => 9, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Marquinhos', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Matuidi', 'goals_club' => 3, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Morata', 'goals_club' => 20, 'goals_career' => 2],
    ['team_id' => 2, 'name' => 'Nainggolan', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Naldo', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Nani', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Nkoulou', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Oscar', 'goals_club' => 21, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'RESTO', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Reus', 'goals_club' => 23, 'goals_career' => 1],
    ['team_id' => 2, 'name' => 'Rodríguez', 'goals_club' => 5, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Sterling', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Sturaro', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Thiago Silva', 'goals_club' => 7, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Verratti', 'goals_club' => 4, 'goals_career' => 0],
    ['team_id' => 2, 'name' => 'Willian', 'goals_club' => 1, 'goals_career' => 0],


    //MANCHESTER UNITED
    ['team_id' => 3, 'name' => 'Alaba', 'goals_club' => 3, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Alcácer', 'goals_club' => 3, 'goals_career' => 5],
    ['team_id' => 3, 'name' => 'Alves', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'André Gomes', 'goals_club' => 1, 'goals_career' => 4],
    ['team_id' => 3, 'name' => 'Arda', 'goals_club' => 12, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Bale', 'goals_club' => 36, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Bastian', 'goals_club' => 4, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Carvajal', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Casemiro', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Depay', 'goals_club' => 39, 'goals_career' => 25],
    ['team_id' => 3, 'name' => 'Deulofeu', 'goals_club' => 3, 'goals_career' => 1],
    ['team_id' => 3, 'name' => 'Di María', 'goals_club' => 16, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Douglas Costa', 'goals_club' => 4, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Drogba', 'goals_club' => 5, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Eriksen', 'goals_club' => 8, 'goals_career' => 5],
    ['team_id' => 3, 'name' => 'Giménez', 'goals_club' => 4, 'goals_career' => 2],
    ['team_id' => 3, 'name' => 'Giovani', 'goals_club' => 9, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Godín', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Halilovic', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Ibrahimović', 'goals_club' => 66, 'goals_career' => 4],
    ['team_id' => 3, 'name' => 'Iniesta', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Isco', 'goals_club' => 25, 'goals_career' => 12],
    ['team_id' => 3, 'name' => 'Jackson', 'goals_club' => 7, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'James', 'goals_club' => 17, 'goals_career' => 15],
    ['team_id' => 3, 'name' => 'Kompany', 'goals_club' => 5, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Lewandowski', 'goals_club' => 38, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Marcelo', 'goals_club' => 4, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Martial', 'goals_club' => 15, 'goals_career' => 8],
    ['team_id' => 3, 'name' => 'Messi', 'goals_club' => 63, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Modric', 'goals_club' => 8, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Muller', 'goals_club' => 48, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Neymar', 'goals_club' => 53, 'goals_career' => 24],
    ['team_id' => 3, 'name' => 'Otamendi', 'goals_club' => 1, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Pepe', 'goals_club' => 3, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Pogba', 'goals_club' => 29, 'goals_career' => 19],
    ['team_id' => 3, 'name' => 'Ramos', 'goals_club' => 7, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'RESTO', 'goals_club' => 122, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Ribery', 'goals_club' => 17, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Robben', 'goals_club' => 27, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Rooney', 'goals_club' => 6, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Sterling', 'goals_club' => 3, 'goals_career' => 1],
    ['team_id' => 3, 'name' => 'Sturridge', 'goals_club' => 18, 'goals_career' => 36],
    ['team_id' => 3, 'name' => 'Suárez', 'goals_club' => 60, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Thiago', 'goals_club' => 11, 'goals_career' => 3],
    ['team_id' => 3, 'name' => 'Varane', 'goals_club' => 5, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Vidal', 'goals_club' => 8, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Walker', 'goals_club' => 0, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Xabi', 'goals_club' => 2, 'goals_career' => 0],
    ['team_id' => 3, 'name' => 'Yaya', 'goals_club' => 1, 'goals_career' => 0],

    //BOCA JUNIORS
    ['team_id' => 4, 'name' => 'Yaya', 'goals_club' => 3, 'goals_career' => 0],
    ['team_id' => 4, 'name' => 'Benzema', 'goals_club' => 5, 'goals_career' => 0],
    ['team_id' => 4, 'name' => 'Bacca', 'goals_club' => 5, 'goals_career' => 0],
    ['team_id' => 4, 'name' => 'Schürrle', 'goals_club' => 7, 'goals_career' => 0],
    ['team_id' => 4, 'name' => 'RESTO', 'goals_club' => 0, 'goals_career' => 0],


    ];
    foreach ($players as $player) {
    	Player::create($player);
    }
  }
}
